In [41]:
# Dhananjai Sharmaimport numpy as np
a = np.array([[1,2,3,4,5],[5,6,7,8,9]])
b = np.array(([[1,2,3,4,5],[5,6,7,8,9]]))
print(a,'\n')
print(b)

[[1 2 3 4 5]
 [5 6 7 8 9]] 

[[1 2 3 4 5]
 [5 6 7 8 9]]


In [20]:
##SUM
c = a + b
print(c)

[[ 2  4  6  8 10]
 [10 12 14 16 18]]


In [11]:
##MULTIPLY
c = a * b
print(c)

[[ 1  4  9 16 25]
 [25 36 49 64 81]]


In [26]:
##DIFF
c = a - b
print(c)

[[0 0 0 0 0]
 [0 0 0 0 0]]


In [27]:
##Printing Specific Rows and Columns
a = np.array([[1,2,3,4,5],[5,6,7,8,9],[9,10,11,12,13]])
print('First Column: ', a[:,0])
print('First Row: ', a[0,:])
print('Third Row: ', a[2,:])
print('Third Column: ', a[:,2])

First Column:  [1 5 9]
First Row:  [1 2 3 4 5]
Third Row:  [ 9 10 11 12 13]
Third Column:  [ 3  7 11]


In [28]:
a

array([[ 1,  2,  3,  4,  5],
       [ 5,  6,  7,  8,  9],
       [ 9, 10, 11, 12, 13]])

In [40]:
##Slicing
print(a,'\n')
print(a[1,1:4],'\n')
print(a[0:2,3:5])

[[ 1  2  3  4  5]
 [ 5  6  7  8  9]
 [ 9 10 11 12 13]] 

[6 7 8] 

[[4 5]
 [8 9]]
