In [38]:
import pandas as pd
import numpy as np

arr_np = np.array([-1,2,-3]*3)

In [39]:
arr_np

array([-1,  2, -3, -1,  2, -3, -1,  2, -3])

In [40]:
arr_np = arr_np.reshape(3,3)
arr_np

array([[-1,  2, -3],
       [-1,  2, -3],
       [-1,  2, -3]])

In [16]:
# Converting to absolute values
arr_np_abs = abs(arr_np)
arr_np_abs

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [20]:
# Negative of matrix values
arr_np_negative = arr_np * -1
arr_np_negative

array([[ 1, -2,  3],
       [ 1, -2,  3],
       [ 1, -2,  3]])

In [21]:
# Removing a particular row 
arr_np1 = np.delete(arr_np, 1, 0)
arr_np1

array([[-1,  2, -3],
       [-1,  2, -3]])

In [22]:
# Removing a particular column
arr_np2 = np.delete(arr_np, 1, 1)
arr_np2

array([[-1, -3],
       [-1, -3],
       [-1, -3]])

In [24]:
# Sum of all elements
summation = np.sum(arr_np)
summation

-6

In [30]:
# Maximum and Minimum values in an array
maximum = np.max(arr_np)
print('Maximum: ', maximum)

minimum = np.min(arr_np)
print('Minimum: ', minimum)

Maximum:  2
Minimum:  -3


In [47]:
# Maximum and Minimum values in a row
arr_np = arr_np ** 2 
maximum = np.max(arr_np[1])
print('Maximum: ', maximum)

minimum = np.min(arr_np[1])
print('Minimum: ', minimum)

Maximum:  9
Minimum:  1


In [53]:
# Sum of a particular row or column
summation = np.sum(arr_np[1])
print('Sum: ', summation)

summation = np.sum(arr_np[:,1])
print('Sum: ', summation)

Sum:  14
Sum:  12


array([4, 4, 4])